### ISSUE TITLE
errors not define in vee-validate's data and the line/bar of v-text-field is not appear in it

### ISSUE THREAD

**Issue by fidellr** [vuetifyjs/docs#210]
1. vee-validate section on https://vuetifyjs.com/components/forms doesn't define the `errors` property and caused an error `Cannot read property 'collect' of undefined`
2. when i make a form/v-form tag and put the v-text-field inside of it, the line of the bar is not showing when i clicked it... or maybe my mistake, but i don't see anything wrong with my code tho..
forgive me if the second one is my mistake/mistype, thanks in advance btw

**Comment by nekosaur** [comment]
1. The `errors` object is something that vee-validate creates automatically

2. This is unrelated to your first problem, and should be addressed at the main vuetify repo

**Comment by fidellr** [comment]
@nekosaur 
1. but it still not working even i keep it in the v-text-field
2.  yes i'm just too lazy to make another issue and is it because we can't export it as a component inside the page of it?

**Comment by nekosaur** [comment]
I've checked the forms page in three browsers (Chrome, Opera, and Edge). None of them report any errors.

If you're having problems in your own code, please open an issue at the vuetify repo.
