### ISSUE TITLE
Time picker disabled color not working

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/docs#263]
quoting @KaelWD from discord:

> There's something funky going on with stylus on docs vs vuetify
> Docs loads `_date-picker.styl` first, then `_pickers.styl`
> on Playground it's the other way around
> So any overrides made in `_date_picker.styl` don't work on docs

**Comment by johnleider** [comment]
This has been resolved.

**Comment by KaelWD** [comment]
The load order is still wrong. 

On docs:
![image](https://user-images.githubusercontent.com/16421948/31052070-c8249e88-a6c5-11e7-80a6-269c9f6fec96.png)

On dev:
![image](https://user-images.githubusercontent.com/16421948/31052249-03cd10dc-a6cb-11e7-8ad5-bbcb01c6f4ca.png)
